let nickFrames = {
  waves = @(n) $"╈{n}╉"
  bullet = @(n) $"◇{n}◈"
  wings = @(n) $"╊{n}╋"
  cannon = @(n) $"◅{n}◆"
  medal = @(n) $"◄{n}◄"
  aircraft = @(n) $"◂{n}◃"
  tank = @(n) $"◀{n}◁"
  ship = @(n) $"▿{n}▿"
  chevron = @(n) $"▾{n}▾"
  clover = @(n) $"◊{n}◊"
  horseshoe = @(n) $"○{n}○"
  winged_diamond = @(n) $"◉{n}◉"
  blazing_sunrise = @(n) $"◌{n}◌"
  palm = @(n) $"●{n}◐"
  machete = @(n) $"◑{n}◒"
  white_squall = @(n) $"◓{n}◔"
  jungle_leaf = @(n) $"◕{n}◖"
  viking_helmet = @(n) $"◗{n}◗"
  iceberg = @(n) $"◘{n}◙"
  wrench = @(n) $"◚{n}◛"
  pipe_wrench = @(n) $"◜{n}◝"
  hammer_and_caliper = @(n) $"◞{n}◟"
  christmas_bauble = @(n) $"◠{n}◡"
  christmas_tree = @(n) $"◢{n}◢"
  impact_direction = @(n) $"◥{n}◤"
  flying_missile = @(n) $"◦{n}◧"
  gun_sight = @(n) $"◨{n}◨"
  clenched_fist = @(n) $"◩{n}◩"
  decor_wtm_helper = @(n) $"◣{n}◣"
  crossed_swords = @(n) $"♠{n}♠"
  spider = @(n) $"◮{n}◮"
  shuriken = @(n) $"☺{n}☺"
  shark = @(n) $"♦{n}♪"
  snake = @(n) $"♣{n}♥"
  flag_on_mountain = @(n) $"♀{n}♂"
  hand_grenade = @(n) $"☻{n}☼"
  bear_head = @(n) $"⋍{n}⋍"
  flame = @(n) $"⊾{n}⊿"
  air_bomb = @(n) $"⋀{n}⋀"
  gas_mask = @(n) $"⋃{n}⋃"
  meteorite = @(n) $"⋁{n}⋂"
  piece_of_cake = @(n) $"⊸{n}⊹"
  cupcake = @(n) $"⊺{n}⊻"
  stars_sparkles = @(n) $"⊼{n}⊽"
  scorpion = @(n) $"⋋{n}⋌"
  corinthian_helmet = @(n) $"◪{n}◫"
  wasp = @(n) $"⋎{n}⋏"
  wolf_head = @(n) $"⋐{n}⋑"
  laurel_wreath = @(n) $"◬{n}◭"
  thunder_cloud = @(n) $"⌢{n}⌣"
  tornado = @(n) $"␀{n}␁"
  aircraft_wings = @(n) $"␂{n}␃"
  tank_tracks = @(n) $"␄{n}␅"
  antitank_hedgehog = @(n) $"⊲{n}⊳"
  sun_and_fighter = @(n) $"⊴{n}⊴"
  radio_tower = @(n) $"⊵{n}⊵"
  missle_strike = @(n) $"⊶{n}⊷"
  star = @(n) $"⊯{n}⊯"
  eagle = @(n) $"⊰{n}⊱"
  justice_scale = @(n) $"♫{n}♫"
  peaceful_atom = @(n) $"♬{n}♬"
  shield = @(n) $"♭{n}♭"
  torch = @(n) $"♮{n}♯"
  snail = @(n) $"♷{n}♸"
  wreath = @(n) $"♹{n}♹"
  shell_barrel = @(n) $"♰{n}♱"
  turret = @(n) $"♲{n}♳"
  shells = @(n) $"♴{n}♴"
  blast = @(n) $"♵{n}♶"
}

let frameNick = @(nick, frameId) nickFrames?[frameId](nick) ?? nick

return {
  nickFrames
  frameNick
}