from "%globalScripts/logs.nut" import *
from "skinTags.nut" import *

let skinsByTag = {
  [FOREST] = [
    "tank_skin_ussr_default_01"
    "cn_camo_green_yellow_black"
    "cn_camo_sand_ltgreen_dkgreen"
    "fin_camo_black_green_brown"
    "fin_camo_black_green_dark"
    "fr_camo_green_brown"
    "fr_camo_vert_olive_arme"
    "ger_camo_bronzegruen"
    "ger_camo_grey"
    "ger_camo_carc"
    "ger_camo_dunkelgelb_green"
    "ger_camo_dunkelgelb_green_braun"
    "ger_camo_dunkelgelb_green_braun_blots_small"
    "ger_camo_dunkelgelb_green_braun_lines"
    "ger_camo_dunkelgelb_green_braun_lines_mhn"
    "ger_camo_hinterhalt_daimler"
    "ger_camo_hinterhalt_man"
    "ger_camo_inside_dark"
    "ger_camo_tiger_green"
    "it_camo_green"
    "it_camo_modern_three_color"
    "it_camo_olive_green"
    "it_camo_threecolor_modern"
    "jp_camo_late_green_brown_yellow_blots"
    "jp_camo_olive"
    "jp_camo_olive_kusairo"
    "jp_camo_post_green"
    "jp_camo_post_multicolor"
    "jp_camo_sdf_green"
    "se_camo_green"
    "se_camo_modern_deform"
    "tl_camo_green_forest"
    "uk_camo_middle_deep_bronze_greens"
    "us_camo_modern_green"
    "uk_camo_standart_modern_bicolor"
    "uk_camo_very_dark_drab"
    "us_camo_dark_green_dark_earth"
    "us_camo_olive"
    "us_camo_olive_drab"
    "us_camo_olive_drab_olive"
    "us_camo_olive_late"
    "usa_modern_seventh_army"
    "usa_modern_summer_verdant"
    "usa_modern_tropical"
    "ussr_camo_dkgreen_ltgreen_brown"
    "ussr_camo_dkgreen_ltgreen_brown_ver_2"
    "ussr_camo_forest_01"
    "ussr_camo_green"
    "ussr_camo_green_ltbrown_lines"
    "ussr_camo_green_new-painty"
    "ussr_modern_forest"
    "ussr_camo_deform"
  ],

  [DESERT] = [
    "fr_camo_desert_storm"
    "fr_camo_green_sand_brown"
    "fr_camo_jaune_sahara"
    "ger_camo_bundeswehr_afgan"
    "ger_camo_dunkelgelb"
    "ger_camo_dunkelgelb_africa"
    "ger_camo_modern_threecolor"
    "ger_camo_tiger"
    "it_camo_desert_modern"
    "rsa_camo_modern_three_color"
    "uk_camo_earth_yellow"
    "uk_camo_light_mud_blue_black"
    "uk_camo_light_mud_slate_grey"
    "uk_camo_light_stone_slate_grey"
    "us_camo_desert_pink_dark_khaki"
    "us_camo_desert_pink_lines"
    "us_camo_desert_pink_olive"
    "us_camo_desert_pink_olive_drab"
    "us_camo_desert_pink_olive_drab_dark_earth"
    "us_camo_desert_pink_olive_drab_dark_earth_black"
    "us_camo_olive_drab_desert_pink_"
    "ussr_camo_czechoslovak_yellow_green"
    "ussr_camo_desert_syrian_green_brown_yellow"
    "ussr_camo_desert_yellow_brown"
    "tl_camo_desert_chopped"
    "isr_camo_sandgray"
    "ussr_t_34_85_zis_53_dislike"
  ],

  [WINTER] = [
    "fin_camo_black_green_white"
    "fr_camo_modern_urban"
    "ger_camo_inside_elfebein"
    "ger_camo_winter_dunkelgelb"
    "ger_camo_winter_lines"
    "ger_camo_winter_waves"
    "ger_camo_winter_waves_bicolor"
    "jp_camo_post_winter"
    "tl_camo_grey_pink_blots"
    "tl_camo_grey_yellow_lines"
    "tl_camo_red_grey_lines"
    "tl_camo_red_grey_chopped"
    "tl_camo_usa_colors"
    "us_camo_inside_light"
    "us_camo_winter_grid"
    "us_camo_winter_olive"
    "ussr_camo_winter"
    "ussr_camo_winter_lines"
    "ussr_camo_winter_net"
    "ussr_modern_winter"
  ],

  [NAVAL] = [
    "camo_b15"
    "camo_bottom_green"
    "camo_crosspromo"
    "camo_dark_wood"
    "camo_deckbasaltgrau"
    "camo_deckgrey"
    "camo_deepdark_wood"
    "camo_fadedgreen"
    "camo_hazegray"
    "camo_hellgrau_50"
    "camo_inside_white"
    "camo_navygrey_5"
    "camo_rot_5"
    "camo_sandy"
    "camo_syntheticblackpaint"
    "camo_warshipdeepgray"
    "camo_wood"

    "camo_3gray_colors_geometry"
    "camo_blackgray_net"
    "camo_blackwhite_geometry"
    "camo_blackyellow_spots"
    "camo_greyblack_geometry"
    "camo_greyblackblue_geometry"
    "camo_sboat_splotch"
    "camo_threegray_spots"

    "camo_blackgray_geometry"
    "camo_blue_geometry"
    "camo_browngray_net"
    "camo_darkgrey_curves"
    "camo_darkgrey_spots"
    "camo_darkgrey_zigzag"
    "camo_ghiglino_spots"
    "camo_greenedges"

    "camo_asiatic_forest"
    "camo_blue_waves"
    "camo_bluegray_spots"
    "camo_darkblue_waves"
    "camo_darkbrown_spots"
    "camo_darkgrey_big_spots"
    "camo_fourgreencolors"
    "camo_redgreen_spots"

    "camo_blackgreen_geometry"
    "camo_bluegray_geometry"
    "camo_bluewaves"
    "camo_greygreen_curves"
    "camo_homefleet_deckhouse"
    "camo_mediterranean_geometry"
    "camo_mtb_spots"
    "camo_nord_bluegreen"
    "camo_polish_bluegeometry"

    "camo_blackgray_spots"
    "camo_blue_spots"
    "camo_designpt328"
    "camo_greenriver_curves"
    "camo_measure_12mod"
    "camo_measure_geometry"
    "camo_modern_nordgeometry"
    "camo_multicolor_cubes"
    "camo_nato_blue_geometry"

    "camo_arctic_minesweeper_block"
    "camo_bluegray_longspot"
    "camo_cross_browngreen"
    "camo_geometry_longdiag"
    "camo_geometry_zheleznyakov"
    "camo_northern_fleet"
    "camo_northern_fleet_contrast"
    "camo_violetgray_geometry"

    "camo_lightblue_splotch"
    "camo_dark_spots"
    "camo_marine_geometry"
    "camo_bluegreen_splotch"
    "camo_arctic_spots"
    "camo_gray_spots"
    "camo_greenwhite_spots"
    "camo_olive_spots"
    "camo_lightblue_geometry"
    "camo_grayriver"
    "camo_darkgray_blotch"
    "camo_blackgray_stripes"
    "camo_disruptive_gray"
    "camo_threegreenspots"
    "camo_black_longdiag"
    "camo_blue_stains"
    "camo_lightgreen_geometry"
    "camo_greencoast"
    "camo_gray_splotch"
    "camo_bluewater_geometry"
    "camo_sboat_fleet"
  ],
}

let skinViewPresets = {}
foreach(tag, list in skinsByTag)
  foreach(id in list) {
    if (id in skinViewPresets) {
      logerr($"Skin preset {id} added twice to skinsByTag")
      continue
    }
    skinViewPresets[id] <- { id, tag, image = $"{id}.avif" }
  }

return freeze(skinViewPresets)
