return {
  JOY_XBOX_REAL_AXIS_L_THUMB_H = 0
  JOY_XBOX_REAL_AXIS_L_THUMB_V = 1
  JOY_XBOX_REAL_AXIS_R_THUMB_H = 2
  JOY_XBOX_REAL_AXIS_R_THUMB_V = 3
  JOY_XBOX_REAL_AXIS_L_TRIGGER = 4
  JOY_XBOX_REAL_AXIS_R_TRIGGER = 5
  JOY_XBOX_REAL_AXIS_LR_TRIGGER = 6
}