return {
  JOY_XBOX_REAL_AXIS_L_THUMB_H = 0
  JOY_XBOX_REAL_AXIS_L_THUMB_V = 1
  JOY_XBOX_REAL_AXIS_R_THUMB_H = 2
  JOY_XBOX_REAL_AXIS_R_THUMB_V = 3
  JOY_XBOX_REAL_AXIS_L_TRIGGER = 4
  JOY_XBOX_REAL_AXIS_R_TRIGGER = 5
  JOY_XBOX_REAL_AXIS_LR_TRIGGER = 6

  JOY_AXIS_MASK = 0x0F 
  AXIS_MODIFIEER_LB = 0x100

  GRAVITY_AXIS_X = 12
  GRAVITY_AXIS_Y = 13
  GRAVITY_AXIS_Z = 14
}
