from "%globalsDarg/darg_library.nut" import *

require("%rGui/levelUp/debugLevelUp.nut")
require("%rGui/debriefing/debriefingWnd.nut")
require("%rGui/levelUp/levelUpWnd.nut")
require("%rGui/attributes/unitAttr/unitAttrWnd.nut")
require("%rGui/attributes/slotAttr/slotAttrWnd.nut")
require("%rGui/attributes/slotAttr/slotExpWnd.nut")
require("%rGui/unitMods/unitModsWnd.nut")
require("%rGui/unitMods/unitModsSlotsWnd.nut")
require("%rGui/unitsTree/unitsTreeWnd.nut")
require("%rGui/unitCustom/unitCustomWnd.nut")
require("%rGui/unitCustom/unitCustomWndNew.nut")
require("%rGui/slotBar/selectUnitToSlotWnd.nut")
require("%rGui/slotBar/slotPresetsWnd.nut")
require("%rGui/quests/questsWnd.nut")
require("%rGui/quests/questRewardsWnd.nut")
require("%rGui/shop/shopWnd.nut")
require("%rGui/queue/queueWnd.nut")
require("%rGui/queue/queuePenaltyWnd.nut")
require("%rGui/unit/debugUnits.nut")
require("%rGui/hudHints/hintsDebug.nut")
require("%rGui/loading/debugLoadingTips.nut")
require("%rGui/notifications/bqEvents.nut")
require("%rGui/notifications/benchmarkResult.nut")
require("%rGui/notifications/allowLimitedConnectionDownload.nut")
require("%rGui/notifications/allowGameAutoUpdate.nut")
require("%rGui/notifications/negativeBalanceWarning.nut")
require("%rGui/notifications/suggestUpdateMsg.nut")
require("%rGui/notifications/suggestLinkEmailMsg.nut")
require("%rGui/notifications/logEventsAfterLogin.nut")
require("%rGui/notifications/levelUpAppsFlyerEvent.nut")
require("%rGui/notifications/infoPopupWnd.nut")
require("%rGui/notifications/allowPushNotification.nut")
require("%rGui/notifications/suggestUhqMsg.nut")
require("%rGui/account/notifyEmailRegistration.nut")
require("%rGui/account/emailLinkRewardState.nut")
require("%rGui/hudHints/shipObstacleWarning.nut")
require("%rGui/hudHints/shipDeathTimer.nut")
require("%rGui/hudHints/leaveZoneTimer.nut")
require("%rGui/hudHints/debuffWarnngs.nut")
require("%rGui/hudHints/killStreakHint.nut")
require("%rGui/hudHints/streakHint.nut")
require("%rGui/hudHints/pickUpItemMsg.nut")
require("%rGui/hudTuning/hudTuningWnd.nut")
require("%rGui/tutorial/tutorialWnd/tutorialWnd.nut")
require("%rGui/tutorial/tutorialAfterFreeReward.nut")
require("%rGui/tutorial/tutorialUnitsResearch.nut")
require("%rGui/tutorial/tutorialArsenal.nut")
require("%rGui/tutorial/tutorialBattlePass.nut")
require("%rGui/tutorial/tutorialMainEvent.nut")
require("%rGui/tutorial/choosingShellsTutorial.nut")
require("%rGui/tutorial/tutorialSlotAttributes.nut")
require("%rGui/tutorial/tutorTreeEvent.nut")
require("%rGui/feedback/rateGameState.nut")
require("%rGui/updater/downloadAddonsWnd.nut")
require("%rGui/updater/downloadMsgCtor.nut")
require("%rGui/report/reportPlayerWnd.nut")
require("%rGui/weaponry/debugBullets.nut")
require("%rGui/unitCustom/unitDecals/debugDecals.nut")
require("%rGui/shop/unseenPurchaseMessage.nut")
require("%rGui/shop/checkPurchases.nut")
require("%rGui/shop/goodsPreview/goodsUnitPreviewWnd.nut")
require("%rGui/shop/goodsPreview/goodsSkinPreviewWnd.nut")
require("%rGui/shop/goodsPreview/goodsPremiumWnd.nut")
require("%rGui/shop/goodsPreview/subscriptionWnd.nut")
require("%rGui/shop/goodsPreview/goodsCurrencyPreviewWnd.nut")
require("%rGui/shop/goodsPreview/goodsLootboxPreviewWnd.nut")
require("%rGui/shop/goodsPreview/goodsSlotsPreviewWnd.nut")
require("%rGui/shop/autoPreviewQueue.nut")
require("%rGui/shop/autoOpenLootboxes.nut")
require("%rGui/shop/lootboxOpenRouletteWnd.nut")
require("%rGui/shop/lootboxPreviewWnd.nut")
require("%rGui/shop/gifts.nut")
require("%rGui/news/newsWnd.nut")
require("%rGui/ads/debugAdsWnd.nut")
require("%rGui/ads/adsPreloaderWnd.nut")
require("%rGui/debugTools/pServerConsoleCmd.nut")
require("%rGui/debugTools/debugGamepadIconsWnd.nut")
require("%rGui/debugTools/debugHudSpam.nut")
require("%rGui/debugTools/debugRewardPlateCompWnd.nut")
require("%rGui/debugTools/debugStreakWnd.nut")
require("%rGui/debugTools/debugFontsWnd.nut")
require("%rGui/debugTools/debugSkins/debugTuneSkinsWnd.nut")
require("%rGui/debugTools/debugMapPoints/mapEditorWnd.nut")
require("%rGui/gameModes/offlineBattlesWnd.nut")
require("%rGui/debugTools/debugLootboxWnd.nut")
require("%rGui/debugTools/localAutoTests.nut")
require("%rGui/unlocks/loginAwardWnd.nut")
require("%rGui/unlocks/achievementsHandler.nut")
require("%rGui/unit/hangarUnitBattleData.nut")
require("%rGui/mainMenu/experienceWnd.nut")
require("%rGui/decorators/decoratorsScene.nut")
require("%rGui/battlePass/battlePassWnd.nut")
require("%rGui/battlePass/bpPurchaseWnd.nut")
require("%rGui/boosters/boostersPurchaseWnd.nut")
require("%rGui/notifications/consent/consentMainWnd.nut")
require("%rGui/notifications/consent/manageOptionsWnd.nut")
require("%rGui/notifications/consent/partnersWnd.nut")
require("%rGui/options/touchSenseOptConvert.nut")
require("%rGui/options/licenseWnd.nut")
require("%rGui/options/chooseMovementControls/chooseMovementControlsWnd.nut")
require("%rGui/contacts/contactsWnd.nut")
require("%rGui/contacts/myContactPresence.nut")
require("%rGui/invitations/invitationsWnd.nut")
require("%rGui/squad/myExtData.nut")
require("%rGui/event/eventWnd.nut")
require("%rGui/event/buyEventCurrenciesWnd.nut")
require("%rGui/event/profileUpdateOnSeasonEnd.nut")
require("%rGui/event/gmEventWnd.nut")
require("%rGui/event/gmEventWithEPWnd.nut")
require("%rGui/event/treeEvent/treeEventWnd.nut")
require("%rGui/leaderboard/lbWnd.nut")
require("%rGui/leaderboard/lbBestBattlesWnd.nut")
require("%rGui/debriefing/debrQuestsMgr.nut")
require("%rGui/debriefing/debrUnitWeapons.nut")
require("%rGui/loading/loadingScreen.nut")
  .setMissionLoadingScreen(require("%rGui/loading/missionLoadingScreen.nut"))
require("%rGui/chat/mpChatHandler.nut")
require("%rGui/levelUp/levelUpRewards.nut")
require("%rGui/levelUp/unitLevelUpRewards.nut")
require("%rGui/consoleCmdAfterLogin.nut")
require("%rGui/hud/indicators/missionIndicatorsMgr.nut")
require("%rGui/unit/upgradeUnitWnd/unitUpgradeWnd.nut")
require("%rGui/dmViewer/protAnalysisOptionsWnd.nut")
require("%rGui/dmViewer/protAnalysisSimulationWnd.nut")
require("%rGui/dmViewer/modeXrayDebugExport.nut")
require("%rGui/syncCurrencies.nut")
require("%rGui/battlePass/eventPassWnd.nut")
require("%rGui/battlePass/eventPassPurchaseWnd.nut")
require("%rGui/battlePass/passScene.nut")
require("%rGui/battlePass/operationPassPurchaseWnd.nut")



let { modalWindowsComponent } = require("%rGui/components/modalWindows.nut")
let { scenesOrder, getTopScene } = require("%rGui/navState.nut")
let { behindScene } = require("%rGui/behindScene.nut")
let { isInBattle, isInMpSession, isInFlightMenu, isMpStatisticsActive
} = require("%appGlobals/clientState/clientState.nut")
let { isInRespawn } = require("%appGlobals/clientState/respawnStateBase.nut")
let { isInSpectatorMode, isInArtilleryMap } = require("%rGui/hudState.nut")
let { compToCompAnimations } = require("%darg/helpers/compToCompAnim.nut")
let mainMenuWnd = require("%rGui/mainMenu/mainMenuWnd.nut")
let respawnWnd = require("%rGui/respawn/respawnWnd.nut")
let hudSpectator = require("%rGui/hud/hudSpectator.nut")
let hudArtilleryMap = require("%rGui/hud/hudArtilleryMap.nut")
let { isVoiceMsgMapSceneOpened, voiceMsgMapScene } = require("%rGui/hud/voiceMsg/hudVoiceMsgMapScene.nut")
let { isTacticalMapSceneOpened, tacticalMapScene } = require("%rGui/hud/tacticalMap/hudTacticalMapScene.nut")
let flightMenu = require("%rGui/flightMenu/flightMenu.nut")
let mpStatisticsWnd = require("%rGui/mpStatistics/mpStatisticsWnd.nut")
let hudBase = require("%rGui/hud/hudBase.nut")
let { sendNewbieBqEvent } = require("%appGlobals/pServer/bqClient.nut")

isInBattle.subscribe(@(v)
  sendNewbieBqEvent(v ? "enterBattle" : "leaveBattle", { status = isInMpSession.get() ? "online" : "offline" }))

let battleScene = @() {
  watch = [isInRespawn, isInSpectatorMode, isInArtilleryMap, isInFlightMenu, isMpStatisticsActive,
    isVoiceMsgMapSceneOpened, isTacticalMapSceneOpened]
  key = {}
  size = flex()
  children = isInFlightMenu.get() ? flightMenu
    : isMpStatisticsActive.get() ? mpStatisticsWnd
    : isInSpectatorMode.get() ? hudSpectator
    : isInRespawn.get() ? respawnWnd
    : isInArtilleryMap.get() ? hudArtilleryMap
    : isVoiceMsgMapSceneOpened.get() ? voiceMsgMapScene
    : isTacticalMapSceneOpened.get() ? tacticalMapScene
    : hudBase
}

return {
  size = flex()
  children = [
    behindScene
    @() {
      watch = [scenesOrder, isInBattle]
      size = flex()
      waitForChildrenFadeOut = true
      children = getTopScene(scenesOrder.get())
        ?? (isInBattle.get() ? battleScene : mainMenuWnd)
    }
    modalWindowsComponent
    compToCompAnimations
  ]
}