const TUTORIAL_UNITS_RESEARCH_ID = "tutorialUnitsResearch"
const TUTORIAL_ARSENAL_ID = "tutorialArsenal"
const TUTORIAL_AFTER_REWARD_ID = "tutorialAfterFreeReward"


return {
  TUTORIAL_UNITS_RESEARCH_ID
  TUTORIAL_ARSENAL_ID
  TUTORIAL_AFTER_REWARD_ID
}