let bulletsImages = {
  ap_tank                             = "shell_apbc_tank"
  apbc_tank                           = "shell_apbc_tank"
  apbc_usa_tank                       = "shell_apbc_tank"
  ap_large_caliber_tank               = "shell_apbc_tank"
  apcbc_solid_medium_caliber_tank     = "shell_apbc_tank"
  apc_solid_medium_caliber_tank       = "shell_apbc_tank"
  aphe_tank                           = "shell_apbc_tank"
  aphebc_tank                         = "shell_apbc_tank"
  apc_tank                            = "shell_apbc_tank"
  apcbc_tank                          = "shell_apbc_tank"
  sap_tank                            = "shell_apbc_tank"
  sapbc_tank                          = "shell_apbc_tank"
  sapcbc_tank                         = "shell_apbc_tank"
  sap_hei                             = "shell_apbc_tank"
  ac_shell_tank                       = "shell_apbc_tank"
  apds_tank                           = "shell_apds_tank"
  apds_early_tank                     = "shell_apds_tank"
  apds_l15_tank                       = "shell_apds_tank"
  he_frag_tank                        = "shell_he_frag_tank"
  he_frag_i_tank                      = "shell_he_frag_tank"
  sap_hei_tank                        = "shell_he_frag_tank"
  he_grenade_tank                     = "shell_he_frag_tank"
  he_frag_fs_tank                     = "shell_he_frag_fs_tank"
  heat_tank                           = "shell_heat_tank"
  heat_fs_tank                        = "shell_heat_fs_tank"
  heat_grenade_tank                   = "shell_heat_grenade_tank"
  hesh_tank                           = "shell_hesh_tank"
  apcr_tank                           = "shell_apcr_tank"
  apds_fs_tank                        = "shell_apdsfs_tank"
  apds_fs_full_body_steel_tank        = "shell_apdsfs_tank"
  apds_autocannon                     = "shell_apdsfs_tank"
  smoke_tank                          = "shell_smoke_tank"
  apds_fs_long_l30_tank               = "shell_apds_fs_long_l30_tank"
  apds_fs_long_tank                   = "shell_apds_fs_long_tank"
  apds_fs_tungsten_caliber_fins_tank  = "shell_apds_fs_tungsten_caliber_fins_tank"
  apds_fs_tungsten_l10_l15_tank       = "shell_apds_fs_tungsten_l10_l15_tank"
  apds_fs_tungsten_small_core_tank    = "shell_apds_fs_tungsten_small_core_tank"
  shell_bullet_belt_tank              = "shell_bullet_belt_tank"
}

let function getBulletImage(bullets){
  if(bullets.len() > 1)
    return "ui/gameuiskin#shell_bullet_belt_tank.avif"
  return bulletsImages?[bullets[0]] ? $"ui/gameuiskin#{bulletsImages?[bullets[0]]}.avif"
   : "ui/unitskin#image_in_progress.avif"
}

return getBulletImage